/*
 * Cloudiator REST Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.cloudiator.rest.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CloudiatorProcessNew
 */
public class CloudiatorProcessNewTest {
    private final CloudiatorProcessNew model = new CloudiatorProcessNew();

    /**
     * Model tests for CloudiatorProcessNew
     */
    @Test
    public void testCloudiatorProcessNew() {
        // TODO: test CloudiatorProcessNew
    }

    /**
     * Test the property 'processType'
     */
    @Test
    public void processTypeTest() {
        // TODO: test processType
    }

    /**
     * Test the property 'schedule'
     */
    @Test
    public void scheduleTest() {
        // TODO: test schedule
    }

    /**
     * Test the property 'task'
     */
    @Test
    public void taskTest() {
        // TODO: test task
    }

    /**
     * Test the property 'taskInterface'
     */
    @Test
    public void taskInterfaceTest() {
        // TODO: test taskInterface
    }

}
