/*
 * Cloudiator REST Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.cloudiator.rest.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.cloudiator.rest.model.Trigger;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for FaasInterfaceAllOf
 */
public class FaasInterfaceAllOfTest {
    private final FaasInterfaceAllOf model = new FaasInterfaceAllOf();

    /**
     * Model tests for FaasInterfaceAllOf
     */
    @Test
    public void testFaasInterfaceAllOf() {
        // TODO: test FaasInterfaceAllOf
    }

    /**
     * Test the property 'functionName'
     */
    @Test
    public void functionNameTest() {
        // TODO: test functionName
    }

    /**
     * Test the property 'sourceCodeUrl'
     */
    @Test
    public void sourceCodeUrlTest() {
        // TODO: test sourceCodeUrl
    }

    /**
     * Test the property 'handler'
     */
    @Test
    public void handlerTest() {
        // TODO: test handler
    }

    /**
     * Test the property 'triggers'
     */
    @Test
    public void triggersTest() {
        // TODO: test triggers
    }

    /**
     * Test the property 'timeout'
     */
    @Test
    public void timeoutTest() {
        // TODO: test timeout
    }

    /**
     * Test the property 'functionEnvironment'
     */
    @Test
    public void functionEnvironmentTest() {
        // TODO: test functionEnvironment
    }

}
