/*
 * Cloudiator REST Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.cloudiator.rest.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.cloudiator.rest.model.ProcessMapping;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for HdfsInterfaceAllOf
 */
public class HdfsInterfaceAllOfTest {
    private final HdfsInterfaceAllOf model = new HdfsInterfaceAllOf();

    /**
     * Model tests for HdfsInterfaceAllOf
     */
    @Test
    public void testHdfsInterfaceAllOf() {
        // TODO: test HdfsInterfaceAllOf
    }

    /**
     * Test the property 'processMapping'
     */
    @Test
    public void processMappingTest() {
        // TODO: test processMapping
    }

}
