/*
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.cloudiator.rest.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets DiscoveryItemState
 */
@JsonAdapter(DiscoveryItemState.Adapter.class)
public enum DiscoveryItemState {
  
  NEW("NEW"),
  
  OK("OK"),
  
  REMOTELY_DELETED("REMOTELY_DELETED"),
  
  LOCALLY_DELETED("LOCALLY_DELETED"),
  
  DISABLED("DISABLED"),
  
  UNKNOWN("UNKNOWN");

  private String value;

  DiscoveryItemState(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static DiscoveryItemState fromValue(String text) {
    for (DiscoveryItemState b : DiscoveryItemState.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<DiscoveryItemState> {
    @Override
    public void write(final JsonWriter jsonWriter, final DiscoveryItemState enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public DiscoveryItemState read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return DiscoveryItemState.fromValue(String.valueOf(value));
    }
  }
}

