/*
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.cloudiator.rest.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.cloudiator.rest.model.TaskInterface;
import io.github.cloudiator.rest.model.Trigger;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;

/**
 * Part of a Task. Represents one function. 
 */
@ApiModel(description = "Part of a Task. Represents one function. ")

public class FaasInterface extends TaskInterface implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("functionName")
  private String functionName = null;

  @SerializedName("sourceCodeUrl")
  private String sourceCodeUrl = null;

  @SerializedName("handler")
  private String handler = null;

  @SerializedName("triggers")
  private List<Trigger> triggers = null;

  @SerializedName("timeout")
  private Integer timeout = 6;

  @SerializedName("functionEnvironment")
  private java.util.Map functionEnvironment = null;

  public FaasInterface functionName(String functionName) {
    this.functionName = functionName;
    return this;
  }

   /**
   * Unique name of the function. 
   * @return functionName
  **/
  @ApiModelProperty(value = "Unique name of the function. ")
  public String getFunctionName() {
    return functionName;
  }

  public void setFunctionName(String functionName) {
    this.functionName = functionName;
  }

  public FaasInterface sourceCodeUrl(String sourceCodeUrl) {
    this.sourceCodeUrl = sourceCodeUrl;
    return this;
  }

   /**
   * URL path to ZIP artifact. 
   * @return sourceCodeUrl
  **/
  @ApiModelProperty(value = "URL path to ZIP artifact. ")
  public String getSourceCodeUrl() {
    return sourceCodeUrl;
  }

  public void setSourceCodeUrl(String sourceCodeUrl) {
    this.sourceCodeUrl = sourceCodeUrl;
  }

  public FaasInterface handler(String handler) {
    this.handler = handler;
    return this;
  }

   /**
   * function in the code to be invoked. 
   * @return handler
  **/
  @ApiModelProperty(value = "function in the code to be invoked. ")
  public String getHandler() {
    return handler;
  }

  public void setHandler(String handler) {
    this.handler = handler;
  }

  public FaasInterface triggers(List<Trigger> triggers) {
    this.triggers = triggers;
    return this;
  }

  public FaasInterface addTriggersItem(Trigger triggersItem) {
    if (this.triggers == null) {
      this.triggers = new ArrayList<Trigger>();
    }
    this.triggers.add(triggersItem);
    return this;
  }

   /**
   * Events on which function will be invoked. 
   * @return triggers
  **/
  @ApiModelProperty(value = "Events on which function will be invoked. ")
  public List<Trigger> getTriggers() {
    return triggers;
  }

  public void setTriggers(List<Trigger> triggers) {
    this.triggers = triggers;
  }

  public FaasInterface timeout(Integer timeout) {
    this.timeout = timeout;
    return this;
  }

   /**
   * Allowed time in seconds for function to finish its task. 
   * minimum: 1
   * @return timeout
  **/
  @ApiModelProperty(value = "Allowed time in seconds for function to finish its task. ")
  public Integer getTimeout() {
    return timeout;
  }

  public void setTimeout(Integer timeout) {
    this.timeout = timeout;
  }

  public FaasInterface functionEnvironment(java.util.Map functionEnvironment) {
    this.functionEnvironment = functionEnvironment;
    return this;
  }

   /**
   * Environment variables passed to function. 
   * @return functionEnvironment
  **/
  @ApiModelProperty(value = "Environment variables passed to function. ")
  public java.util.Map getFunctionEnvironment() {
    return functionEnvironment;
  }

  public void setFunctionEnvironment(java.util.Map functionEnvironment) {
    this.functionEnvironment = functionEnvironment;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FaasInterface faasInterface = (FaasInterface) o;
    return Objects.equals(this.functionName, faasInterface.functionName) &&
        Objects.equals(this.sourceCodeUrl, faasInterface.sourceCodeUrl) &&
        Objects.equals(this.handler, faasInterface.handler) &&
        Objects.equals(this.triggers, faasInterface.triggers) &&
        Objects.equals(this.timeout, faasInterface.timeout) &&
        Objects.equals(this.functionEnvironment, faasInterface.functionEnvironment) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(functionName, sourceCodeUrl, handler, triggers, timeout, functionEnvironment, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FaasInterface {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    functionName: ").append(toIndentedString(functionName)).append("\n");
    sb.append("    sourceCodeUrl: ").append(toIndentedString(sourceCodeUrl)).append("\n");
    sb.append("    handler: ").append(toIndentedString(handler)).append("\n");
    sb.append("    triggers: ").append(toIndentedString(triggers)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    functionEnvironment: ").append(toIndentedString(functionEnvironment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

