/*
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.cloudiator.rest.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The type of this LRR
 */
@JsonAdapter(LRRType.Adapter.class)
public enum LRRType {
  
  VIRTUALMACHINEREQUEST("VirtualMachineRequest");

  private String value;

  LRRType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static LRRType fromValue(String text) {
    for (LRRType b : LRRType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<LRRType> {
    @Override
    public void write(final JsonWriter jsonWriter, final LRRType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public LRRType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return LRRType.fromValue(String.valueOf(value));
    }
  }
}

