/*
 * Cloudiator REST Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.cloudiator.rest.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * Represents a runtime for a Platform component, e.g. Java, PHP, Tomcat
 */
@ApiModel(description = "Represents a runtime for a Platform component, e.g. Java, PHP, Tomcat")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-01-13T10:47:33.672+01:00[Europe/Berlin]")
public class NewPlatformRuntime implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  /**
   * the specific runtime language
   */
  @JsonAdapter(LanguageEnum.Adapter.class)
  public enum LanguageEnum {
    PHP("PHP"),
    
    JAVA("JAVA"),
    
    RUBY("RUBY"),
    
    PYTHON("PYTHON");

    private String value;

    LanguageEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static LanguageEnum fromValue(String value) {
      for (LanguageEnum b : LanguageEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<LanguageEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final LanguageEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public LanguageEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return LanguageEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_LANGUAGE = "language";
  @SerializedName(SERIALIZED_NAME_LANGUAGE)
  private LanguageEnum language;

  public static final String SERIALIZED_NAME_LANGUAGE_VERSION = "languageVersion";
  @SerializedName(SERIALIZED_NAME_LANGUAGE_VERSION)
  private Double languageVersion;

  /**
   * specifies the runtime type
   */
  @JsonAdapter(RuntimeTypeEnum.Adapter.class)
  public enum RuntimeTypeEnum {
    STANDALONE("standalone"),
    
    SERVER("server");

    private String value;

    RuntimeTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RuntimeTypeEnum fromValue(String value) {
      for (RuntimeTypeEnum b : RuntimeTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<RuntimeTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RuntimeTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RuntimeTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return RuntimeTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_RUNTIME_TYPE = "runtimeType";
  @SerializedName(SERIALIZED_NAME_RUNTIME_TYPE)
  private RuntimeTypeEnum runtimeType;

  public static final String SERIALIZED_NAME_VERSION = "version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private Double version;


  public NewPlatformRuntime name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * human readable name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "human readable name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public NewPlatformRuntime language(LanguageEnum language) {
    
    this.language = language;
    return this;
  }

   /**
   * the specific runtime language
   * @return language
  **/
  @ApiModelProperty(required = true, value = "the specific runtime language")

  public LanguageEnum getLanguage() {
    return language;
  }


  public void setLanguage(LanguageEnum language) {
    this.language = language;
  }


  public NewPlatformRuntime languageVersion(Double languageVersion) {
    
    this.languageVersion = languageVersion;
    return this;
  }

   /**
   * language version number
   * @return languageVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "11.0", value = "language version number")

  public Double getLanguageVersion() {
    return languageVersion;
  }


  public void setLanguageVersion(Double languageVersion) {
    this.languageVersion = languageVersion;
  }


  public NewPlatformRuntime runtimeType(RuntimeTypeEnum runtimeType) {
    
    this.runtimeType = runtimeType;
    return this;
  }

   /**
   * specifies the runtime type
   * @return runtimeType
  **/
  @ApiModelProperty(required = true, value = "specifies the runtime type")

  public RuntimeTypeEnum getRuntimeType() {
    return runtimeType;
  }


  public void setRuntimeType(RuntimeTypeEnum runtimeType) {
    this.runtimeType = runtimeType;
  }


  public NewPlatformRuntime version(Double version) {
    
    this.version = version;
    return this;
  }

   /**
   * the version of the specified type
   * @return version
  **/
  @ApiModelProperty(example = "2.0", required = true, value = "the version of the specified type")

  public Double getVersion() {
    return version;
  }


  public void setVersion(Double version) {
    this.version = version;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewPlatformRuntime newPlatformRuntime = (NewPlatformRuntime) o;
    return Objects.equals(this.name, newPlatformRuntime.name) &&
        Objects.equals(this.language, newPlatformRuntime.language) &&
        Objects.equals(this.languageVersion, newPlatformRuntime.languageVersion) &&
        Objects.equals(this.runtimeType, newPlatformRuntime.runtimeType) &&
        Objects.equals(this.version, newPlatformRuntime.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, language, languageVersion, runtimeType, version);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewPlatformRuntime {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    languageVersion: ").append(toIndentedString(languageVersion)).append("\n");
    sb.append("    runtimeType: ").append(toIndentedString(runtimeType)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

