/*
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.cloudiator.rest.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.cloudiator.rest.model.NodeCandidate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * A request to start a node. 
 */
@ApiModel(description = "A request to start a node. ")

public class NodeRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("groupName")
  private String groupName = null;

  @SerializedName("nodeCandidate")
  private NodeCandidate nodeCandidate = null;

  public NodeRequest groupName(String groupName) {
    this.groupName = groupName;
    return this;
  }

   /**
   * An (optional) name for all nodes starting in this group 
   * @return groupName
  **/
  @ApiModelProperty(value = "An (optional) name for all nodes starting in this group ")
  public String getGroupName() {
    return groupName;
  }

  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  public NodeRequest nodeCandidate(NodeCandidate nodeCandidate) {
    this.nodeCandidate = nodeCandidate;
    return this;
  }

   /**
   * Get nodeCandidate
   * @return nodeCandidate
  **/
  @ApiModelProperty(value = "")
  public NodeCandidate getNodeCandidate() {
    return nodeCandidate;
  }

  public void setNodeCandidate(NodeCandidate nodeCandidate) {
    this.nodeCandidate = nodeCandidate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NodeRequest nodeRequest = (NodeRequest) o;
    return Objects.equals(this.groupName, nodeRequest.groupName) &&
        Objects.equals(this.nodeCandidate, nodeRequest.nodeCandidate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupName, nodeCandidate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NodeRequest {\n");
    
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    nodeCandidate: ").append(toIndentedString(nodeCandidate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

