/*
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.cloudiator.rest.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;
import java.io.Serializable;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Type of OS Architecture
 */
@JsonAdapter(OperatingSystemArchitecture.Adapter.class)
public enum OperatingSystemArchitecture {
  
  AMD64("AMD64"),
  
  UNKOWN("UNKOWN"),
  
  I386("I386"),
  
  ARM("ARM");

  private String value;

  OperatingSystemArchitecture(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static OperatingSystemArchitecture fromValue(String text) {
    for (OperatingSystemArchitecture b : OperatingSystemArchitecture.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<OperatingSystemArchitecture> {
    @Override
    public void write(final JsonWriter jsonWriter, final OperatingSystemArchitecture enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public OperatingSystemArchitecture read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return OperatingSystemArchitecture.fromValue(String.valueOf(value));
    }
  }
}

