/*
 * Cloudiator REST Api
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.github.cloudiator.rest.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.github.cloudiator.rest.model.Behaviour;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * Subtype of Behaviour Represents a service runtime behaviour 
 */
@ApiModel(description = "Subtype of Behaviour Represents a service runtime behaviour ")

public class ServiceBehaviour extends Behaviour implements Serializable {
  private static final long serialVersionUID = 1L;

  @SerializedName("restart")
  private Boolean restart = null;

  public ServiceBehaviour restart(Boolean restart) {
    this.restart = restart;
    return this;
  }

   /**
   * True if the service should be restarted failure, false if not 
   * @return restart
  **/
  @ApiModelProperty(value = "True if the service should be restarted failure, false if not ")
  public Boolean isRestart() {
    return restart;
  }

  public void setRestart(Boolean restart) {
    this.restart = restart;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceBehaviour serviceBehaviour = (ServiceBehaviour) o;
    return Objects.equals(this.restart, serviceBehaviour.restart) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(restart, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceBehaviour {\n");
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("    restart: ").append(toIndentedString(restart)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

