/*
 * Cloudiator REST Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: daniel.baur@uni-ulm.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.cloudiator.rest.api;

import io.github.cloudiator.rest.ApiException;
import io.github.cloudiator.rest.model.Text;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SecurityApi
 */
@Ignore
public class SecurityApiTest {

    private final SecurityApi api = new SecurityApi();

    
    /**
     * 
     *
     * Decrypts the given string
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void decryptTest() throws ApiException {
        String text = null;
        Text response = api.decrypt(text);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteSecureTest() throws ApiException {
        String key = null;
        api.deleteSecure(key);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Encrypts the given string
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void encryptTest() throws ApiException {
        String text = null;
        Text response = api.encrypt(text);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * Retrieves the stored value. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveSecureTest() throws ApiException {
        String key = null;
        Text response = api.retrieveSecure(key);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void storeSecureTest() throws ApiException {
        String key = null;
        Text value = null;
        Text response = api.storeSecure(key, value);

        // TODO: test validations
    }
    
}
